version: "3.8"

services:
  nginx:
    image: nginx-pet-projects
    container_name: nginx-pet-projects-container
    build:
      context: .
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    networks:
      - shared-pet

networks:
  shared-pet:
    external: true
